### ISSUE TITLE
What an input matrix (mat_value) should be like for the features of mutations and copy number alterations?

### ISSUE THREAD

**Issue by lincj1994** [korkutlab/reflect#11]
Hi. @lixubinp 
Thanks for developing a cool tool.
I'm wondering what the input (mat_value) should be like when the features included mutations and copy number alterations? Should it be categorized (for example, 1 for mut and 0 for wild-type, or 1 for amplification, 0 for neutral, and -1 for deletion) or continuous values?
Thanks.

**Comment by lixubinp** [comment]
Thanks for your interest and using our package. 

The input mat_value can be either continuous or discrete. For gene expression or protein expression, we use continuous values; whereas for mutation or copy number alterations, we use discrete values. Mutations are discretized to {0, 1}, where mutant = 1, wild type = 0. The copy number alterations are discretized to {-1, 0, 1}, representing deletion, wild type, and amplification, respectively. 

In addition, you may consider choosing the dissimilarity parameter based on the data modality. You can choose either "squared.distance" or "absolute.value". In the REFLECT paper and resource, to smoothen small differences and strengthen big differences, the squared Euclidean distance was employed as the distance measure for continuous data types (i.e., protein and mRNA expressions). For discrete data types (i.e., mutations and copy number alterations), where only a small finite set of values exists, that is, {-1, 0, 1}, we used the absolute difference as their distance measures.

**Comment by lincj1994** [comment]
Thanks for your reply.
So that means I cannot put both discrete and continuous values in the same matrix?

**Comment by lixubinp** [comment]
In the REFLECT resource, we processed discrete and continuous features separately. In theory, you can put both discrete and continuous values in the same matrix. Since they are numerical values, the algorithm can handle it. The resulted signatures would depend on variation of each feature, regardless of continuous or discrete values. If the variations of continuous features dominates that of discrete features, none or very few of discrete features would be selected.
